server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}
    session:
      timeout: 30m
  port: ${SERVER_PORT:8080}
spring:
  autoconfigure:
    exclude:
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
  thymeleaf:
    cache: ${THYMELEAF_ENABLE_CACHE:off}
    mode: ${THYMELEAF_MODE:HTML}
    prefix: ${THYMELEAF_PREFIX:classpath:/templates/}
    suffix: ${THYMELEAF_SUFFIX:.html}
    encoding: UTF-8
    servlet:
      content-type: ${THYMELEAF_CONTENT_TYPE:text/html}
    enabled: ${THYMELEAF_ENABLED:on}
  task:
    scheduling:
      pool:
        size: 80
      thread-name-prefix: elegant-scheduler-
      shutdown:
        await-termination: on
        await-termination-period: PT3M
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 60MB
      enabled: on
  main:
    banner-mode: off
  messages:
    basename: i18n/messages,i18n/errors,i18n/warnings,i18n/validation
  jackson:
    time-zone: ${TIMEZONE:UTC}
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: off
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  application:
    name: ${APPLICATION_NAME:nls-api}
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      connection-timeout: 30000
      read-only: off
      minimum-idle: ${DATASOURCE_MINIMUM_IDLE:2}
      maximum-pool-size: ${DATASOURCE_MAXIMUM_POOL_SIZE:10}
      auto-commit: on
      max-lifetime: 600000
      idle-timeout: 300000
      connection-test-query: select 1
      validation-timeout: 1500
      pool-name: ${spring.application.name}-HikariCP
  mvc:
    log-request-details: on
    static-path-pattern: /static/**
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full
    java:
      enabled: on
    env:
      enabled: on
    os:
      enabled: off
    process:
      enabled: off
logging:
  level:
    jp.onehr.elegantapi.business.auth.mapper: TRACE
    web: DEBUG
info:
  app:
    name: ${spring.application.name}
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: ${SA_TOKEN_NAME:auth-token}
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: ${SA_TOKEN_TIMEOUT:2592000}
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: ${SA_TOKEN_ACTIVE_TIMEOUT:-1}
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: ${SA_TOKEN_IS_CONCURRENT:on}
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: ${SA_TOKEN_IS_SHARE:off}
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: ${SA_TOKEN_STYLE:uuid}
  # 是否输出操作日志
  is-log: ${SA_TOKEN_IS_LOG:off}
  # 是否在初始化配置时在控制台打印版本字符画
  is-print: off
# 文档 https://mybatis.org/mybatis-3/index.html
mybatis:
  mapper-locations: ${MYBATIS_MAPPER_LOCATIONS:-classpath:/mapper/**/*.xml}
  configuration:
    aggressive-lazy-loading: off
    # 当查询数据为空时字段返回为null，不设置这个字段为true的话查询的数据为null时，字段将被隐藏
    call-setters-on-nulls: on
    lazy-loading-enabled: on
    local-cache-scope: session
    use-column-label: on
  type-handlers-package: jp.onehr.elegantapi.common.handler.typehandler.postgresql
#decorator:
#  datasource:
#    enabled: on
#    datasource-proxy:
#      multiline: on
#      slow-query:
#        logger-name: SLOW-QUERY-LOGGER
#        enable-logging: on
#      json-format: off
#      format-sql: off
#    p6spy:
#      log-format: '%(executionTime)ms|%(category)|connection%(connectionId)|%(sqlSingleLine)'
#      logging: file
#      log-file: p6spy-slow-query.log
